build(lint): enabled more linters

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Continuous Integration
+name: CI
 
 on:
   push:
@@ -12,42 +12,57 @@ on:
 permissions:
   contents: read
 
+env:
+  GO_VERSION: '1.23'
+  GOLANGCI_LINT_VERSION: 'v1.61'
+
 jobs:
-  linters:
+  lint:
     name: Run linters
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-go@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-go@v5
         with:
-          go-version: '1.21'
-      - uses: actions/cache@v3
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
+          go-version: ${{ env.GO_VERSION }}
+          cache-dependency-path: "**/*.sum"
       - name: golangci-lint
-        uses: golangci/golangci-lint-action@v3
+        uses: golangci/golangci-lint-action@v6
         with:
-          version: v1.61
+          version: ${{ env.GOLANGCI_LINT_VERSION }}
 
-  unit-tests:
+  test:
     name: Run unit tests
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        go: ['1.21']
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-go@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-go@v5
         with:
-          go-version: ${{ matrix.go }}
-      - uses: actions/cache@v3
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
+          go-version: ${{ env.GO_VERSION }}
+          cache-dependency-path: "**/*.sum"
       - name: go test
-        run: go test -race ./...
+        run: go test -fullpath -race ./...
+
+  complete:
+    name: 'Complete'
+    runs-on: ubuntu-latest
+    needs: [lint, test]
+    if: ${{ always() }}
+    steps:
+      - name: 'Check if all jobs passed'
+        run: |
+          needs_json='${{ toJSON(needs) }}'
+          job_names=$(echo "$needs_json" | jq -r 'keys[]')
+          failed_jobs=()
+          for job in $job_names; do
+            job_status=$(echo "$needs_json" | jq -r '."'${job}'".result')
+            if [ "$job_status" != "success" ]; then
+              failed_jobs+=($job)
+            fi
+          done
+          if [ ${#failed_jobs[@]} -ne 0 ]; then
+            echo "The following jobs failed: ${failed_jobs[@]}"
+            exit 1
+          else
+            echo "All jobs passed."
+          fi
